repos:
  # NOTE: Removed end-of-file-fixer, trailing-whitespace hooks (too noisy / low signal)
  # and the custom go mod tidy drift hook (caused repeated friction). Keep only
  # size + line-ending sanity plus lint & tests for higher-signal checks.
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: mixed-line-ending
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.61.0
    hooks:
      - id: golangci-lint
        name: golangci-lint (modules)
        entry: >-
          bash -c "for m in engine cli tools/apireport; do echo '[lint] $m'; (cd $m && golangci-lint run ./...) || exit 1; done"
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: go-test-modules
        name: go test (short) all modules
        entry: >-
          bash -c "for m in engine cli tools/apireport; do echo '[test] $m'; (cd $m && go test -short ./...) || exit 1; done"
        language: system
        pass_filenames: false
      # go-mod-tidy-check removed (manual 'make tidy' in CI / release process is sufficient)
