name: builds

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go-version: [1.25]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Clear Go mod cache
        run: go clean -modcache

      - name: Workspace sync
        run: go work sync

      - name: Build modules
        run: |
          for m in engine cli tools/apireport; do
            echo "==> build $m";
            (cd $m && go build ./... ) || exit 1;
          done

      - name: Test modules
        run: |
          for m in engine cli tools/apireport; do
            echo "==> test $m";
            (cd $m && go test ./... ) || exit 1;
          done
