name: cli-smoke

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.25
      - name: Workspace sync
        run: go work sync
      - name: Build CLI
        run: (cd cli && go build ./cmd/ariadne)
      - name: Run short crawl
        run: |
          set -euo pipefail
          echo "Running short crawl with metrics + health enabled"
          go run ./cli/cmd/ariadne -seeds https://example.com -enable-metrics -metrics :19090 -health :19091 -snapshot-interval 0 | head -n 20
      # - name: Probe metrics endpoint
      #   run: |
      #     echo "Waiting for metrics endpoint..."
      #     for i in $(seq 1 30); do
      #       if curl -fsS http://localhost:19090/metrics | grep -q ariadne_build_info; then
      #         echo "Metrics endpoint OK"; exit 0; fi; sleep 0.2; done; echo "Metrics endpoint did not respond" >&2; exit 1
      # - name: Probe health endpoint
      #   run: |
      #     echo "Waiting for health endpoint..."
      #     for i in $(seq 1 30); do
      #       if curl -fsS http://localhost:19091/healthz | grep -q 'status'; then
      #         echo "Health endpoint OK"; exit 0; fi; sleep 0.2; done; echo "Health endpoint did not respond" >&2; exit 1
