name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.25]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Clear Go mod cache
        run: go clean -modcache

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        run: go mod download

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: go build -v ./...

      - name: Run tests
        run: go test -v -race -coverprofile=coverage.out ./...

      - name: Check test coverage
        run: |
          go tool cover -func=coverage.out
          COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print substr($3, 1, length($3)-1)}')
          echo "Total test coverage: $COVERAGE%"
          # TODO: Re-enable coverage requirement when coverage improves
          # Currently at ~58%, target is 80%+
          # if (( $(echo "$COVERAGE < 80" | bc -l) )); then
          #   echo "❌ Test coverage is below 80%"
          #   exit 1
          # else
          #   echo "✅ Test coverage is above 80%"
          # fi

      - name: Verify API report freshness
        run: |
          echo "Regenerating API report and checking for drift..."
          cp API_REPORT.md /tmp/API_REPORT.prev
          go run ./cmd/apireport -out API_REPORT.md
          if ! diff -u /tmp/API_REPORT.prev API_REPORT.md; then
            echo "❌ API_REPORT.md is out of date. Run 'make api-report' and commit the changes." >&2
            exit 1
          fi
          echo "✅ API_REPORT.md is up to date"
